CREATE TABLE locations (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    address varchar(50) NOT NULL,
    phone char(20) NOT NULL,     -- format "+1 888 888 8888"
    sales_tax NUMBER(4,2) NOT NULL
);

CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL,
    email varchar(40) NOT NULL,
    membership number(1) NOT NULL,
    points number(7) DEFAULT 0,
    active number(1) DEFAULT 1,
    CONSTRAINT customer_membership_chk
        CHECK (membership BETWEEN 0 AND 1),
    CONSTRAINT customer_active_chk
        CHECK (active BETWEEN 0 AND 1)
);

CREATE TABLE phone_numbers (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    phone char(20), --- format "+1888-888-8888"
    customer_id NUMBER,
    CONSTRAINT cust_phone
        FOREIGN KEY (customer_id)
        REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE cards (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    brand varchar(40) NOT NULL,
    name varchar(30) NOT NULL,
    card_number char(20),
    expr_date char(7) NOT NULL, -- format 2024-08
    cvv char(3) NOT NULL,
    active number(1) DEFAULT 1,
    CONSTRAINT fk_cards
        FOREIGN KEY (customer_id)
        REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT card_active_chk
        CHECK (active BETWEEN 0 AND 1)
);

CREATE TABLE items (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name varchar(50),
    price NUMBER(10,2)
);

CREATE TABLE customer_creations (
    id NUMBER PRIMARY KEY,
    creator varchar(30),
    CONSTRAINT cc_fk
        FOREIGN KEY (id)
        REFERENCES items(id) ON DELETE CASCADE
);

CREATE TABLE signature_items (
    id NUMBER PRIMARY KEY,
    CONSTRAINT sig_fk
        FOREIGN KEY (id)
        REFERENCES items(id) ON DELETE CASCADE
);

CREATE TABLE recipes (
    recipe_id NUMBER,
    ingredient_id NUMBER,
    quantity NUMBER(2),
    CONSTRAINT recipe_target_fk
        FOREIGN KEY (recipe_id)
        REFERENCES customer_creations(id) ON DELETE CASCADE,
    CONSTRAINT recipe_ingredient_fk
        FOREIGN KEY (ingredient_id)
        REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT recipe_pk
        PRIMARY KEY (recipe_id, ingredient_id),
    CONSTRAINT recipe_quantity_chk
        CHECK (quantity > 0)
);

CREATE TABLE menus (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name varchar(20)
);

CREATE TABLE local_menus (
    menu_id NUMBER,
    location_id NUMBER,
    CONSTRAINT lm_menu_fk
        FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE,
    CONSTRAINT lm_loc_fk
        FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
    CONSTRAINT lm_pk
        PRIMARY KEY (menu_id, location_id)
);

CREATE TABLE menu_items (
    menu_id NUMBER,
    item_id NUMBER,
    CONSTRAINT menu_id_fk
        FOREIGN KEY (menu_id)
        REFERENCES menus(id) ON DELETE CASCADE,
    CONSTRAINT item_id_fk
        FOREIGN KEY (item_id)
        REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT menu_item_pk
        PRIMARY KEY (menu_id, item_id)
);

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    location_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    payment_id NUMBER,
    status NUMBER,
    total NUMBER(6,2),
    CONSTRAINT loc_fk
        FOREIGN KEY (location_id)
        REFERENCES locations(id) ON DELETE CASCADE,
    CONSTRAINT customer_fk
        FOREIGN KEY (customer_id)
        REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT pay_fk
        FOREIGN KEY (payment_id)
        REFERENCES cards(id) ON DELETE CASCADE,
    CONSTRAINT status_chk
        CHECK (status BETWEEN 0 AND 4) -- CANCELLED, RECIEVED, IN-PROGRESS, WAITING-FOR PICKUP, COMPLETED
);

CREATE TABLE order_items (
    order_id NUMBER,
    item_id NUMBER,
    quantity NUMBER NOT NULL,
    price NUMBER(5,2) NOT NULL, --individual item cost. This needs to be set like this to account for price adjustments based on location
    CONSTRAINT order_id_fk
        FOREIGN KEY (order_id)
        REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT order_item_fk
        FOREIGN KEY (item_id)
        REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT order_items_pk
        PRIMARY KEY (order_id, item_id),
    CONSTRAINT order_quantity_chk
        CHECK (quantity > 0)
);

CREATE TABLE price_change (
    item_id number,
    location_id number,
    price number(5,2),
    CONSTRAINT pc_item_fk
        FOREIGN KEY (item_id)
        REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT pc_location_fk
        FOREIGN KEY (location_id)
        REFERENCES locations(id) ON DELETE CASCADE,
    CONSTRAINT pc_pk
        PRIMARY KEY (item_id, location_id)
);

CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    location_id NUMBER NOT NULL,
    role NUMBER(2)
    CONSTRAINT role_range_chk 
        CHECK (role BETWEEN 1 AND 2), -- only two roles are implemented, location manager and general manager
    CONSTRAINT employee_fk
        FOREIGN KEY (location_id)
        REFERENCES locations(id) ON DELETE CASCADE
);

-- VIEWS

CREATE VIEW signature_item_view AS
SELECT items.id, items.name, items.price FROM items
JOIN signature_items ON items.id = signature_items.id;

CREATE VIEW customer_creations_view AS
SELECT i.id, i.name, i.price, c.creator
FROM items i
JOIN customer_creations c ON i.id = c.id;

CREATE VIEW ingredients AS
SELECT * FROM items
WHERE NOT EXISTS (
    SELECT sig.id FROM signature_items sig WHERE sig.id = items.id
);

CREATE VIEW order_item_view AS
SELECT oi.order_id, oi.item_id, i.name, oi.quantity, oi.price FROM
order_items oi
JOIN items i ON oi.item_id = i.id;

CREATE VIEW order_customer_view AS
SELECT o.id, o.created_at, o.location_id, o.customer_id, c.name, o.payment_id, o.status, o.total
FROM orders o
JOIN customers c ON o.customer_id = c.id;

CREATE OR REPLACE VIEW all_items_class_view AS ( -- this is the nastiest most inefficient thing ive ever seen.. at least you know it wasn't made by ai...
    SELECT i.id, i.name, i.price, 'CUSTOMER_CREATION' AS item_type, c.creator AS "specific_attribute"
    FROM items i
    JOIN customer_creations c ON c.id=i.id
    
    UNION ALL
    
    SELECT i.id, i.name, i.price, 'SIGNATURE' as item_type, NULL as "specific_attribute"
    FROM items i
    JOIN signature_items s ON s.id = i.id

    UNION ALL
    SELECT i.id, i.name, i.price, 'INGREDIENT' as item_type, NULL as "specific_attribute"
    FROM ingredients i
    MINUS
    SELECT i.id, i.name, i.price, 'INGREDIENT' as item_type, NULL as "specific_attribute"
    FROM customer_creations_view i
);

CREATE VIEW local_menu_view AS
SELECT m.id, m.name, lm.location_id
FROM menus m
JOIN local_menus lm ON m.id=lm.menu_id;

-- This trigger allows us to update the cost of signature items when ingredients are added or removed from them
-- Please note that for this specific query, AI sources were consulted (as one may look at stack overflow...) in order to understand how to obtain the values of the target rows
create or replace TRIGGER upd_item_price
AFTER INSERT OR DELETE ON recipes
FOR EACH ROW
DECLARE 
    ingredient_price NUMBER;
    added_cost NUMBER;
BEGIN

    IF INSERTING THEN
        SELECT price INTO ingredient_price
        FROM items
        WHERE id = :NEW.ingredient_id;

        added_cost := ingredient_price * :NEW.quantity;

    ELSIF DELETING THEN
        SELECT price INTO ingredient_price
        FROM items
        WHERE id = :OLD.ingredient_id;

        added_cost := ingredient_price * :OLD.quantity * -1;

    END IF;

    UPDATE items
    SET price = nvl(price, 0) + added_cost
    WHERE items.id = nvl(:NEW.recipe_id, :OLD.recipe_id);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
    NULL;

END;
/

-- Add a trigger that adds an item to the master menu
CREATE OR REPLACE TRIGGER master_menu
AFTER INSERT ON items
FOR EACH ROW
BEGIN
    INSERT INTO menu_items (menu_id, item_id)
    VALUES (1, :NEW.id);
END;
/

-- Updates an order's total based on the price of it's items and its local sales tax
create or replace TRIGGER upd_order_price
AFTER INSERT OR DELETE ON order_items
FOR EACH ROW
DECLARE 
    item_price NUMBER;
    added_cost NUMBER;
    upd_loc_id NUMBER;
    local_sales_tax NUMBER;
BEGIN

    SELECT location_id INTO upd_loc_id
    FROM orders
    WHERE orders.id = nvl(:NEW.order_id, :OLD.order_id);

    SELECT sales_tax INTO local_sales_tax
    FROM locations
    WHERE id = upd_loc_id;

    IF INSERTING THEN
        SELECT price INTO item_price
        FROM items
        WHERE id = :NEW.item_id;

        added_cost := :NEW.price * :NEW.quantity * local_sales_tax;

    ELSIF DELETING THEN
        SELECT price INTO item_price
        FROM items
        WHERE id = :OLD.item_id;

        added_cost := :OLD.price * :OLD.quantity * -1 * local_sales_tax;
    END IF;

    UPDATE orders
    SET total = nvl(total, 0) + added_cost
    WHERE orders.id = nvl(:NEW.order_id, :OLD.order_id);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
    NULL;

END;
/

create or replace TRIGGER upd_customer_points
AFTER INSERT OR DELETE ON orders
FOR EACH ROW
DECLARE 
    added_points NUMBER;
    customer_membership NUMBER;
BEGIN

    added_points := floor(:NEW.total / 2);
    IF added_points > 9999999 THEN
        added_points := 9999999;
    END IF;
    
    SELECT membership INTO customer_membership
    FROM customers
    WHERE id = :NEW.customer_id;
    
    IF customer_membership = 1 THEN --only track points for members.
        UPDATE customers
        SET points = nvl(points, 0) + added_points
        WHERE id = :NEW.customer_id;
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
    NULL;

END;
/