CREATE TABLE locations (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    address varchar(50) NOT NULL,
    phone char(20) NOT NULL,     -- format "+1 888 888 8888"
    sales_tax NUMBER(4,2) NOT NULL
);

CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL,
    email varchar(40) NOT NULL,
    membership number(1) NOT NULL,
    points number(7) DEFAULT 0,
    active number(1) DEFAULT 1,
    CONSTRAINT membership_chk
        CHECK (membership BETWEEN 0 AND 1)
    CONSTRAINT active_chk
        CHECK (active BETWEEN 0 AND 1)
);

CREATE TABLE phone_numbers (
    phone char(20), --- format "+1888-888-8888"
    customer_id NUMBER,
    CONSTRAINT cust_phone
        FOREIGN KEY (customer_id)
        REFERENCES customers(id),
    CONSTRAINT pk_phonenum
        PRIMARY KEY (phone, customer_id)
);

CREATE TABLE cards (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    brand varchar(40) NOT NULL,
    name varchar(30) NOT NULL,
    card_number char(20),
    expr_date char(7) NOT NULL, -- format 2024-08
    cvv char(3) NOT NULL,
    CONSTRAINT fk_cards
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
);

CREATE TABLE items (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name varchar(50),
    price NUMBER(5,2)
);

CREATE TABLE customer_creations (
    id NUMBER PRIMARY KEY,
    creator varchar(30),
    CONSTRAINT cc_fk
        FOREIGN KEY (id)
        REFERENCES items(id)
);

CREATE TABLE signature_items (
    id NUMBER PRIMARY KEY,
    CONSTRAINT sig_fk
        FOREIGN KEY (id)
        REFERENCES items(id)
);

CREATE TABLE recipes (
    recipe_id NUMBER,
    ingredient_id NUMBER,
    quantity NUMBER(2),
    CONSTRAINT recipe_target_fk
        FOREIGN KEY (recipe_id)
        REFERENCES customer_creations(id),
    CONSTRAINT recipe_ingredient_fk
        FOREIGN KEY (ingredient_id)
        REFERENCES items(id),
    CONSTRAINT recipe_pk
        PRIMARY KEY (recipe_id, ingredient_id)
);

CREATE TABLE menus (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name varchar(20)
);

CREATE TABLE menu_items (
    menu_id NUMBER,
    item_id NUMBER,
    CONSTRAINT menu_id_fk
        FOREIGN KEY (menu_id)
        REFERENCES menus(id),
    CONSTRAINT item_id_fk
        FOREIGN KEY (item_id)
        REFERENCES items(id),
    CONSTRAINT menu_item_pk
        PRIMARY KEY (menu_id, item_id)
);

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    location_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    payment_id NUMBER,
    CONSTRAINT loc_fk
        FOREIGN KEY (location_id)
        REFERENCES locations(id),
    CONSTRAINT customer_fk
        FOREIGN KEY (customer_id)
        REFERENCES customers(id),
    CONSTRAINT pay_fk
        FOREIGN KEY (payment_id)
        REFERENCES cards(id)
);

CREATE TABLE order_items (
    order_id NUMBER,
    item_id NUMBER,
    CONSTRAINT order_id_fk
        FOREIGN KEY (order_id)
        REFERENCES orders(id),
    CONSTRAINT order_item_fk
        FOREIGN KEY (item_id)
        REFERENCES items(id),
    CONSTRAINT order_items_pk
        PRIMARY KEY (order_id, item_id)
);

CREATE TABLE price_change (
    item_id number,
    location_id number,
    price number(5,2),
    CONSTRAINT pc_item_fk
        FOREIGN KEY (item_id)
        REFERENCES items(id),
    CONSTRAINT pc_location_fk
        FOREIGN KEY (location_id)
        REFERENCES locations(id),
    CONSTRAINT pc_pk
        PRIMARY KEY (item_id, location_id)
);

CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    location_id NUMBER NOT NULL,
    role NUMBER(2)
    CONSTRAINT role_range_chk 
        CHECK (role BETWEEN 1 AND 2), -- only two roles are implemented, location manager and general manager
    CONSTRAINT employee_fk
        FOREIGN KEY (location_id)
        REFERENCES locations(id)
)